# Generated by Django 3.1.2 on 2021-03-31 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210330_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='category',
            field=models.CharField(choices=[('Startup Member', 'Startup Member'), ('Investor', 'Investor')], default='Startup Member', max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='field_of_interest',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Textiles', 'Textiles'), ('Sculptures and Paintings', 'Sculptures and Paintings'), ('Sports', 'Sports'), ('Music', 'Music'), ('Food and Health', 'Food and Health')], default='NONE', max_length=50),
        ),
    ]
